# -*- coding: utf-8 -*-
"""1010~4110E006.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17PtFvjoZi-vbyCQ_7LOx2AmQSf-pkvfe
"""

x = 121654
y = 2.2154
z = 121j

print(type(x))
print(type(y))
print(type(z))

x = 1.0E
y = 1.0E1
a = 1.0E12
z = -54.35

print(type(x))
print(type(y))
print(type(z))

x = float(1+210)

y = int(2.32)

z = complex(1.10)

print(x)
print(y)
print(z)

print(type(x))
print(type(y))
print(type(z))

import random

print(random.randrange(10, 100))

a = "Hello, World!"
print(a[0])
print(a[2])
print(a[5])
print(a[7])
print(a[11])

a = "hi,fsdgjsfdgg"
print(len(a))

quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {1} dollars for {0} pieces of item {2}."
print(myorder.format(quantity, itemno, price))

txt = "We are the so-called "KOALA" from the north."
print(txt)

txt = "We are the so-called \"KOALA\" from the north."
print(txt)

thislist = ["ab", "cd", "ef", "gh", "ij"]

print(thislist)

thislist = list(("apple", "banana", "banana"))
print(thislist)

thislist = set(("apple", "banana", "banana"))
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist[1] = "這個取代第二個取代"

print(thislist)

thislist = ["ab", "cd", "ef"]

thislist.insert(2, "塞指定數後面")

print(thislist)

thisdict =	{
  "apple": "Food",
  "coconut": "fruit",
  "Lei": 2003
}
print(thisdict)

thisdict =	{
  "apple": "Food",
  "coconut": "fruit",
  "Lei": 20023,
  "Lei": 2003
}
print(thisdict)

thisdict =	{
  "apple": "Food",
  "coconut": "fruit",
  
  "Lei": 2003
}

thisdict["Lei"] = 6530

print(thisdict)

thisdict =	{
  "apple": "Food",
  "coconut": "fruit",
  "Lei": 2003
}

thisdict["SFSD"] = 6530

print(thisdict)

thisdict =	{
  "apple": "Food",
  "coconut": "fruit",
  "Lei": 2003
}

thisdict.pop("Lei")

print(thisdict)

thisdict =	{
  "apple": "Food",
  "coconut": "fruit",
  "Lei": 2003
}
for x in thisdict:
  print(x)